// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/provider.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/provider.go -destination=mock/service/provider_mock.go -package=service
//

// Package service is a generated GoMock package.
package service
