// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/auth.go

// Package repo is a generated GoMock package.
package repo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/lantonster/askme/internal/model"
)

// MockAuthRepo is a mock of AuthRepo interface.
type MockAuthRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepoMockRecorder
}

// MockAuthRepoMockRecorder is the mock recorder for MockAuthRepo.
type MockAuthRepoMockRecorder struct {
	mock *MockAuthRepo
}

// NewMockAuthRepo creates a new mock instance.
func NewMockAuthRepo(ctrl *gomock.Controller) *MockAuthRepo {
	mock := &MockAuthRepo{ctrl: ctrl}
	mock.recorder = &MockAuthRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepo) EXPECT() *MockAuthRepoMockRecorder {
	return m.recorder
}

// AddUserAccessToken mocks base method.
func (m *MockAuthRepo) AddUserAccessToken(c context.Context, userId int64, accessToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserAccessToken", c, userId, accessToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserAccessToken indicates an expected call of AddUserAccessToken.
func (mr *MockAuthRepoMockRecorder) AddUserAccessToken(c, userId, accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserAccessToken", reflect.TypeOf((*MockAuthRepo)(nil).AddUserAccessToken), c, userId, accessToken)
}

// GetAccessTokenByVisitToken mocks base method.
func (m *MockAuthRepo) GetAccessTokenByVisitToken(c context.Context, visitToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenByVisitToken", c, visitToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessTokenByVisitToken indicates an expected call of GetAccessTokenByVisitToken.
func (mr *MockAuthRepoMockRecorder) GetAccessTokenByVisitToken(c, visitToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenByVisitToken", reflect.TypeOf((*MockAuthRepo)(nil).GetAccessTokenByVisitToken), c, visitToken)
}

// GetUserCacheByAccessToken mocks base method.
func (m *MockAuthRepo) GetUserCacheByAccessToken(c context.Context, accessToken string) (*model.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCacheByAccessToken", c, accessToken)
	ret0, _ := ret[0].(*model.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCacheByAccessToken indicates an expected call of GetUserCacheByAccessToken.
func (mr *MockAuthRepoMockRecorder) GetUserCacheByAccessToken(c, accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCacheByAccessToken", reflect.TypeOf((*MockAuthRepo)(nil).GetUserCacheByAccessToken), c, accessToken)
}

// SetUserCache mocks base method.
func (m *MockAuthRepo) SetUserCache(c context.Context, accessToken string, user *model.UserInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserCache", c, accessToken, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserCache indicates an expected call of SetUserCache.
func (mr *MockAuthRepoMockRecorder) SetUserCache(c, accessToken, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserCache", reflect.TypeOf((*MockAuthRepo)(nil).SetUserCache), c, accessToken, user)
}
