// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/provider.go
//
// Generated by this command:
//
//	mockgen -source=internal/repo/provider.go -destination=mock/repo/provider_mock.go -package=repo
//

// Package repo is a generated GoMock package.
package repo
