server:
  http:
    debug: false
    addr: 0.0.0.0:80
    shutdown_timeout: 1m
swagger:
  show: true
  protocal: http
  host: 127.0.0.1:80
ui:
  base_url: ""
uploads:
  path: .data/uploads
logger:
  level: -1
  file_name: .askme.log
  max_age: 3
  max_size: 100
  max_backups: 10
  compress: true
i18n:
  bundle_dir: .data/i18n