server:
  http:
    debug: false
    addr: 0.0.0.0:80
    shutdown_timeout: 1m
swagger:
  show: true
  protocal: http
  host: 127.0.0.1:80
ui:
  base_url: ""
uploads:
  path: .data/uploads
logger:
  level: -1
  file_name: .askme.log
  max_age: 3
  max_size: 100
  max_backups: 10
  compress: true
i18n:
  bundle_dir: .data/i18n
mysql:
  debug: false
  addr: 127.0.0.1:3306
  user: root
  password: 123456
  db_name: askme
redis:
  addr: 127.0.0.1:6379
  user: root
  password: