definitions:
  handler.ResponseBody:
    properties:
      code:
        description: http code
        type: integer
      data:
        description: response data
      msg:
        description: response message
        type: string
      reason:
        description: reason key
        type: string
    type: object
  schema.RegisterUserByEmailReq:
    properties:
      e_mail:
        description: 邮箱
        maxLength: 500
        type: string
      name:
        description: 用户名
        maxLength: 30
        minLength: 2
        type: string
      pass:
        description: 密码
        maxLength: 32
        minLength: 8
        type: string
    required:
    - e_mail
    - name
    - pass
    type: object
  schema.RegisterUserByEmailRes:
    properties:
      access_token:
        description: 访问令牌
        type: string
      avatar:
        description: 头像
        type: string
      createdAt:
        type: integer
      deletedAt:
        type: integer
      displayName:
        description: 昵称
        type: string
      email:
        description: 邮箱
        type: string
      id:
        type: integer
      ipInfo:
        description: IP 地址
        type: string
      lastLoginDate:
        description: 上次登录时间
        type: integer
      mailStatus:
        description: 邮箱状态
        type: string
      password:
        description: 密码
        type: string
      role_id:
        description: 角色 ID
        type: integer
      status:
        description: 用户状态
        type: string
      suspendedAt:
        description: 被禁言的时间
        type: integer
      updatedAt:
        type: integer
      username:
        description: 用户名
        type: string
      visit_token:
        description: 访问令牌
        type: string
    type: object
  schema.VerifyEmailReq:
    properties:
      code:
        description: 验证码
        maxLength: 500
        type: string
    required:
    - code
    type: object
  schema.VerifyEmailRes:
    properties:
      access_token:
        description: 访问令牌
        type: string
      avatar:
        description: 头像
        type: string
      createdAt:
        type: integer
      deletedAt:
        type: integer
      displayName:
        description: 昵称
        type: string
      email:
        description: 邮箱
        type: string
      id:
        type: integer
      ipInfo:
        description: IP 地址
        type: string
      lastLoginDate:
        description: 上次登录时间
        type: integer
      mailStatus:
        description: 邮箱状态
        type: string
      password:
        description: 密码
        type: string
      role_id:
        description: 角色 ID
        type: integer
      status:
        description: 用户状态
        type: string
      suspendedAt:
        description: 被禁言的时间
        type: integer
      updatedAt:
        type: integer
      username:
        description: 用户名
        type: string
      visit_token:
        description: 访问令牌
        type: string
    type: object
info:
  contact: {}
paths:
  /askme/api/v1/user/email/verification:
    post:
      consumes:
      - application/json
      description: 邮箱验证
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.VerifyEmailReq'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/handler.ResponseBody'
            - properties:
                data:
                  $ref: '#/definitions/schema.VerifyEmailRes'
              type: object
      summary: 邮箱验证
      tags:
      - User
  /askme/api/v1/user/register/email:
    post:
      consumes:
      - application/json
      description: 通过邮箱注册账号
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.RegisterUserByEmailReq'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/handler.ResponseBody'
            - properties:
                data:
                  $ref: '#/definitions/schema.RegisterUserByEmailRes'
              type: object
      summary: 通过邮箱注册账号
      tags:
      - User
swagger: "2.0"
