// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/lantonster/askme/internal/conf"
	"github.com/lantonster/askme/internal/controller"
	"github.com/lantonster/askme/internal/middleware"
	"github.com/lantonster/askme/internal/router"
	"github.com/lantonster/askme/internal/server"
	"github.com/lantonster/askme/internal/service/uploads"
)

// Injectors from wire.go:

func Init() *server.Server {
	config := conf.NewConfig()
	userController := controller.NewUserController()
	askMeRouter := router.NewAskMeRouter(userController)
	swaggerRouter := router.NewSwaggerRouter(config)
	uiRouter := router.NewUiRouter(config)
	uploadsRouter := router.NewUploadsRouter(config)
	uploadsService := uploads.NewUploadsService(config)
	avatarMiddleware := middleware.NewAvatarMiddleware(config, uploadsService)
	serverServer := server.NewHttpServer(config, askMeRouter, swaggerRouter, uiRouter, uploadsRouter, avatarMiddleware)
	return serverServer
}
